[CmdletBinding()]
param(
    [string]$ScopeGuardResult = "",
    [string]$WarningSummary = "",
    [string]$WarningSummaryPath = ""
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptRoot "..\..")

function Get-GitLines {
    param([string[]]$GitArgs)

    $previousErrorActionPreference = $ErrorActionPreference
    try {
        $ErrorActionPreference = "Continue"
        $output = & git @GitArgs 2>$null
    }
    finally {
        $ErrorActionPreference = $previousErrorActionPreference
    }

    if ($null -eq $output) {
        return @()
    }

    return @($output | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
}

function Normalize-RepoPath {
    param([string]$Path)

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return ""
    }

    $normalized = $Path -replace "\\", "/"
    while ($normalized.StartsWith("./", [System.StringComparison]::Ordinal)) {
        $normalized = $normalized.Substring(2)
    }
    while ($normalized.StartsWith("/", [System.StringComparison]::Ordinal)) {
        $normalized = $normalized.Substring(1)
    }

    return $normalized
}

function ConvertTo-MarkdownList {
    param([string[]]$Lines)

    if ($null -eq $Lines -or $Lines.Count -eq 0) {
        return "- None"
    }

    return ($Lines | ForEach-Object { "- ``$_``" }) -join [Environment]::NewLine
}

function Get-WarningSummaryLines {
    param(
        [string]$InlineSummary,
        [string]$SummaryPath
    )

    if (-not [string]::IsNullOrWhiteSpace($InlineSummary)) {
        return @($InlineSummary -split "(`r`n|`n|`r)" | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    }

    if (-not [string]::IsNullOrWhiteSpace($SummaryPath)) {
        $fullPath = $SummaryPath
        if (-not [System.IO.Path]::IsPathRooted($fullPath)) {
            $fullPath = Join-Path $repoRoot $fullPath
        }

        if (Test-Path -LiteralPath $fullPath -PathType Leaf) {
            return @(Get-Content -LiteralPath $fullPath | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
        }
    }

    return @()
}

Push-Location $repoRoot
try {
    $statusDir = Join-Path $repoRoot "docs\p7_status"
    New-Item -ItemType Directory -Force -Path $statusDir | Out-Null

    $reportPath = Join-Path $statusDir "p7_status_latest.md"
    $relativeReportPath = Normalize-RepoPath ($reportPath.Substring($repoRoot.Path.Length).TrimStart([char[]]@("\", "/")))
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
    $branch = (& git branch --show-current).Trim()
    if ([string]::IsNullOrWhiteSpace($branch)) {
        $branch = "(detached or unknown)"
    }

    $latestCommit = (& git log -1 --oneline 2>$null)
    if ([string]::IsNullOrWhiteSpace($latestCommit)) {
        $latestCommit = "(no commit found)"
    }

    $gitStatus = Get-GitLines @("status", "--short")
    $diffFiles = Get-GitLines @("diff", "--name-only", "HEAD", "--")
    $untrackedFiles = Get-GitLines @("ls-files", "--others", "--exclude-standard")
    $changedFiles = @(
        (@($diffFiles) + @($untrackedFiles)) |
            ForEach-Object { Normalize-RepoPath $_ } |
            Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
            Sort-Object -Unique
    )
    if ($changedFiles -notcontains $relativeReportPath) {
        $changedFiles = @($changedFiles + $relativeReportPath | Sort-Object -Unique)
    }

    if ([string]::IsNullOrWhiteSpace($ScopeGuardResult)) {
        $ScopeGuardResult = "not provided"
    }

    $warningSummaryLines = Get-WarningSummaryLines -InlineSummary $WarningSummary -SummaryPath $WarningSummaryPath

    $content = @"
# P7 Status Report

Generated: $timestamp

Generated by: ``tools/p7/write_p7_status_report.ps1``

## Branch

``$branch``

## Latest Commit

``$latestCommit``

## Scope Guard Result

``$ScopeGuardResult``

## Warning Summary

$(ConvertTo-MarkdownList -Lines $warningSummaryLines)

## Git Status

$(ConvertTo-MarkdownList -Lines $gitStatus)

## Changed Files Against HEAD

$(ConvertTo-MarkdownList -Lines $changedFiles)

## Notes

- Add human or review notes here after inspecting the preflight result.
"@

    Set-Content -LiteralPath $reportPath -Value $content -Encoding UTF8
    Write-Host "P7 status report written: $relativeReportPath"
    exit 0
}
finally {
    Pop-Location
}
